version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  testPages: 
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/testPages/*.cy.js
          install-browsers: true
  testsAPI: 
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/apitests/*.cy.js
          install-browsers: true
  elementInteractions: 
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/elementInteractions/*.cy.js
          install-browsers: true      